### ISSUE TITLE
Light not changing

### ISSUE THREAD

**Issue by mattbruman** [entrippy/OctoPrint-OctoHue#14]
I have everything set up correctly as far as I can tell, I was able to send commands through the api to change the light, but after setting up Octohue printer state is not changing the light color.
<img width="413" alt="Capture2" src="https://user-images.githubusercontent.com/43623584/73702934-42660680-46bc-11ea-826c-210ef56d4d87.PNG">
<img width="599" alt="Capture1" src="https://user-images.githubusercontent.com/43623584/73702935-42660680-46bc-11ea-810c-ba2c7327979f.PNG">

**Comment by entrippy** [comment]
Not that i think its suspect, but just so i have a better understanding of your setup, can you tell me what kind of light you are using? 

Do you get any output from octohue in your log files?

**Comment by bkonings** [comment]
I have the same issue, in the logfile it reads:

2020-02-04 19:29:01,232 - octoprint.plugin - ERROR - Error while calling plugin octohue
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/plugin/__init__.py", line 219, in call_plugin
    result = getattr(plugin, method)(*args, **kwargs)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_octohue/__init__.py", line 72, in on_event
    self.rgb(self._settings.get(['connectedc']),bri=255)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_octohue/__init__.py", line 47, in rgb
    return self.set_state(state)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_octohue/__init__.py", line 54, in set_state
    self.pbridge.lights[self._settings.get(['lampid'])].state(**state)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/qhue/qhue.py", line 43, in __call__
    r = requests.put(url, data=json.dumps(kwargs, default=list), timeout=self.timeout)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/requests/api.py", line 131, in put
    return request('put', url, data=data, **kwargs)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/pi/oprint/local/lib/python2.7/site-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/requests/models.py", line 390, in prepare_url
    raise InvalidURL("Invalid URL %r: No host supplied" % url)
InvalidURL: Invalid URL u'http:///api//lights/4/state': No host supplied

Now I know I have the Hue Bridge Address filled, it seems to me that should have been the host name.

**Comment by bkonings** [comment]
Hmm, seems rebooting octoprint fixed the issue for me

**Comment by mattbruman** [comment]
Another reboot fixed here as well, weird since I rebooted after installing, guess it needs another after setup.

**Comment by entrippy** [comment]
Thanks for documenting that a reboot fixed it. Really strange that it took two reboots to make the magic happen.

Glad to hear its up and working now.
