### ISSUE TITLE
Plugin "installed" but not seen by Octoprint (install Unknown)

### ISSUE THREAD

**Issue by Tobjiaz** [entrippy/OctoPrint-OctoHue#52]
**Hi,**

i saw others having the same issue but their solution didnt work for me.
Its installing the Plugin normally (via UI and via ssh console didnt work at all) but the Pluginmanagementlog says "unknown installed".
After restarting OctoPrint i cant find OctoHue in Plugins list and redoing it several times doesnt help either.

I already tried issue solution #39 #16 & #12 but nothing helped.
Using RaspPi 3B+, OctoPrint 1.9.3, Python 3.9.2, OctoPi* 1.0.0cam (build 2023.10.09.154319)
Maybe im doing something wrong?
Where can i find the log?

**Thanks for help :)**

**Comment by coreyms** [comment]
I have the same issue.

**Comment by coreyms** [comment]
Sorry, I originally hit send too early. I'm not one of those people that says it's broken without detail!

**Comment by entrippy** [comment]
@Tobjiaz @coreyms , I have a new release in the works that removes the need for colormath and also numpy, so it should resolve this bug. Unfortunately for you I decided to bundle this fix in with me adding support for a new pairing and configureation flow plus support for power management via hue plug switches.

The config flow is done, however I'm just starting on the power management now, but hopefully it will be quick.

**Comment by entrippy** [comment]
ahh... actually, yes, this might be a side effect of me adding colourmath to requirements.txt. I will revert that asap

**Comment by gtenney99** [comment]
Having a similar problem to coreyms

fresh install of octopi 1.0/octoprint 1.10.2 on a Rpi 4 4GB

Install via the gui it says it successfully installs but is missing from the GUI after the reboot.

doing a manual install from the CLI, results in the following error

`
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
matrix-client 0.4.0 requires urllib3~=1.21, but you have urllib3 2.2.2 which is incompatible.
Successfully installed Babel-2.12.1 Click-8.1.7 Flask-Assets-2.1.0 Flask-Babel-3.1.0 Flask-Limiter-3.8.0 Flask-Login-0.6.3 Jinja2-3.1.4 MarkupSafe-2.1.5 OctoHue-0.6.0 OctoPrint-1.10.2 OctoPrint-FileCheck-2024.3.27 OctoPrint-FirmwareCheck-2021.10.11 OctoPrint-PiSupport-2023.10.10 PyYAML-6.0.2 argon2-cffi-23.1.0 argon2-cffi-bindings-21.2.0 async-timeout-4.0.3 blinker-1.6.3 cachelib-0.10.2 certifi-2024.8.30 cffi-1.17.1 charset-normalizer-3.3.2 class-doc-0.2.6 colorlog-6.8.2 colormath-3.0.0 deprecated-1.2.14 emoji-2.12.1 feedparser-6.0.11 filetype-1.2.0 flask-2.2.5 frozendict-2.4.4 future-0.18.3 idna-3.8 ifaddr-0.2.0 importlib-metadata-8.4.0 importlib-resources-6.4.4 itsdangerous-2.2.0 limits-3.13.0 markdown-3.4.4 markdown-it-py-3.0.0 mdurl-0.1.2 more-itertools-10.4.0 netaddr-0.8.0 netifaces-0.11.0 networkx-3.2.1 numpy-2.0.2 oauthlib-3.2.2 ordered-set-4.1.0 packaging-24.1 passlib-1.7.4 pathvalidate-2.5.2 pkginfo-1.11.1 psutil-5.9.8 pycparser-2.22 pydantic-1.10.16 pygments-2.18.0 pylru-1.2.1 pyserial-3.5 pytz-2024.1 qhue-2.0.1 regex-2024.7.24 requests-2.32.3 requests-oauthlib-2.0.0 rich-13.8.0 sarge-0.1.7.post1 semantic-version-2.10.0 sentry-sdk-1.45.1 setuptools-74.1.1 sgmllib3k-1.0.0 tornado-6.2 typing-extensions-4.12.2 unidecode-1.3.8 urllib3-2.2.2 watchdog-2.3.1 webassets-2.0 websocket-client-1.6.1 werkzeug-2.2.3 wheel-0.44.0 wrapt-1.15.0 zeroconf-0.133.0 zipp-3.20.1 zipstream-ng-1.7.1
`

and in the octoprint log I'm seeing the following error


`2024-09-04 18:24:14,874 - octoprint.plugin.core - ERROR - Error loading plugin octohue
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.9/site-packages/numpy/_core/__init__.py", line 23, in <module>
    from . import multiarray
  File "/home/pi/oprint/lib/python3.9/site-packages/numpy/_core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/home/pi/oprint/lib/python3.9/site-packages/numpy/_core/overrides.py", line 8, in <module>
    from numpy._core._multiarray_umath import (
ImportError: libopenblas.so.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.9/site-packages/numpy/__init__.py", line 114, in <module>
    from numpy.__config__ import show as show_config
  File "/home/pi/oprint/lib/python3.9/site-packages/numpy/__config__.py", line 4, in <module>
    from numpy._core._multiarray_umath import (
  File "/home/pi/oprint/lib/python3.9/site-packages/numpy/_core/__init__.py", line 49, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "/home/pi/oprint/bin/python"
  * The NumPy version is: "2.0.2"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: libopenblas.so.0: cannot open shared object file: No such file or directory


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint/plugin/core.py", line 1297, in _import_plugin
    module = _load_module(module_name, spec)
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint/plugin/core.py", line 52, in _load_module
    return imp.load_module(name, f, filename, details)
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint/vendor/imp.py", line 238, in load_module
    return load_package(name, filename)
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint/vendor/imp.py", line 212, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint_octohue/__init__.py", line 4, in <module>
    from colormath.color_objects import XYZColor, sRGBColor
  File "/home/pi/oprint/lib/python3.9/site-packages/colormath/color_objects.py", line 8, in <module>
    import numpy
  File "/home/pi/oprint/lib/python3.9/site-packages/numpy/__init__.py", line 119, in <module>
    raise ImportError(msg) from e
ImportError: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.
`

**Comment by shileski** [comment]
I am experiencing this issue also.  I have tried a couple of suggestions including installing libatlas-base-dev as well as uninstalling and re-installing Numbpy, as well as installing from a URL instead, and using the terminal to force reinstall OctoHue, however nothing seems to be working. It acted like it installed properly in Safe Mode, however when i reboot in regular mode it's not there.  It's only removable when you boot in Safe Mode. I'm using a Raspberry Pi 3b+., Octopi Version 1.0.0, OctoPrint version 1.10.3

**Comment by Lefo16** [comment]
I am also facing this issue. Tried everything also. Will 0.7.0 be released soon to fix this?

Thanks.
